version: '3.2'

services:
  app:
    image: modjular/modjular-piwigo:latest
    build: .
    ports:
      - "80"
    volumes:
      - pictures:/pictures
      - log:/config/log
      - galleries:/config/www/gallery/galleries
      - data:/config/www/gallery/_data
      - upload:/config/www/gallery/upload
      - plugins:/config/www/gallery/plugins
      - themes:/config/www/gallery/themes
      - template-extension:/config/www/gallery/template-extension
      - local:/config/www/gallery/local

volumes:
  pictures:
  log:
  galleries:
  data:
  upload:
  plugins:
  themes:
  template-extension:
  local:
