version: '3'

services:

  modjular-piwigo:
    build: .
    image: modjular/modjular-piwigo:latest
    ports:
      - 80:80
      - 9443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - piwig-conf:/config

volumes:
  piwig-conf:
